/**
 * Every lucide-react-native icon used anywhere in the app, in one place.
 * Components should import `Icons` from here instead of importing icon
 * components directly from 'lucide-react-native' — this keeps the set of
 * icons in use auditable at a glance and avoids the same icon being
 * imported under different names in different files.
 */
import {
  ArrowDown,
  ArrowRight,
  ArrowUp,
  BarChart3,
  Calendar,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Dumbbell,
  Flame,
  Hash,
  Heart,
  HeartPulse,
  House,
  Infinity as InfinityLucideIcon,
  LayoutGrid,
  Lightbulb,
  LineChart,
  Medal,
  Menu,
  Minus,
  MoreHorizontal,
  PersonStanding,
  Plus,
  Repeat,
  Ruler,
  Search,
  Shuffle,
  Sparkles,
  Star,
  Target,
  Timer,
  Trash2,
  TrendingUp,
  Trophy,
  Type,
  Users,
  Wind,
  Zap,
  Info,
  Share2,
  type LucideIcon,
} from 'lucide-react-native';

export const Icons = {
  arrowDown: ArrowDown,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  barChart: BarChart3,
  calendar: Calendar,
  checkCircle: CheckCircle2,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  clock: Clock,
  dumbbell: Dumbbell,
  flame: Flame,
  hash: Hash,
  heart: Heart,
  heartPulse: HeartPulse,
  house: House,
  infinity: InfinityLucideIcon,
  info: Info,
  layoutGrid: LayoutGrid,
  lightbulb: Lightbulb,
  lineChart: LineChart,
  medal: Medal,
  menu: Menu,
  minus: Minus,
  moreHorizontal: MoreHorizontal,
  personStanding: PersonStanding,
  plus: Plus,
  repeat: Repeat,
  ruler: Ruler,
  search: Search,
  share: Share2,
  shuffle: Shuffle,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  timer: Timer,
  trash: Trash2,
  trendingUp: TrendingUp,
  trophy: Trophy,
  type: Type,
  users: Users,
  wind: Wind,
  zap: Zap,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof Icons;
export type { LucideIcon };
